### ISSUE TITLE
Pod Dependency

### ISSUE THREAD

**Issue by rhvall** [smoope/SwiftyTraverson#4]
Hello!!

I am trying to construct a pod spec and I am using SwiftyTraverson in my project. However, when I run "pod install" on another project that depends on mine, it breaks because it does not find all the dependencies from the cocoa pods repository, which in this case is SwiftyTraverson, and also I can not use directly.

Are there any plans to include this repository into the cocoa pod list??

PS: Meanwhile, I will see if this works:
http://stackoverflow.com/questions/16905112/cocoapods-dependency-in-pod-spec-not-working

**Comment by vicmosin** [comment]
Hi there,
actually the reason of using git as a pod source was mostly testing period.. Now it looks pretty stable so I will start the process..
Will keep you updated

**Comment by rhvall** [comment]
Thanks,

If anyone arrives here and it is still missing from the repository list, I solved the problem as follows:
1.- Download the project or clone it from github, I placed it in the folder "Dependencies"
2.-In "My Project" spec, I had it as a normal dependency

> ...
> s.dependency 'SwiftyTraverson'
> ...

3.- In the "Example Project" cocoa pod file, I added it as a pod, but linked from the original reference:

> ...
> pod 'SwiftyTraverson', :path => 'MyProject/Dependencies/SwiftyTraverson'
> ...

That way, I was able to link and compile correctly on using "MyProject" as a pod from the "ExampleProject".

**Comment by vicmosin** [comment]
@rhvall 
https://cocoapods.org/pods/SwiftyTraverson
